model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularACModel
  shaping_reward: 0
  use_args: false
name: craft_modular-4-0-rope
recipes: resources/craft/recipes.yaml
seed: 4
trainer:
  n_train: 30
  hints: resources/craft/rope.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: CraftWorld
