model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularACModel
  shaping_reward: 0
  use_args: false
name: craft_modular-9-0-cloth
recipes: resources/craft/recipes.yaml
seed: 9
trainer:
  hints: resources/craft/cloth.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  n_train: 30
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: CraftWorld
