model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularACModel
  shaping_reward: 0.1
  use_args: false
name: craft_modular-2-forcestop-0.1-axe
recipes: resources/craft/recipes.yaml
seed: 2
trainer:
  hints: resources/craft/axe.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: CraftWorld
