model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularACModel
  shaping_reward: 0
  use_args: false
name: craft_modular-0-forcestop-0-gem
recipes: resources/craft/recipes.yaml
seed: 0
trainer:
  hints: resources/craft/gem.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: CraftWorld
