model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularActorModularCriticModel
  shaping_reward: 0
  use_args: false
name: craft_mamc-5-forcestop-0-bridge
recipes: resources/craft/recipes.yaml
seed: 5
trainer:
  n_train: 30
  hints: resources/craft/bridge.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: CraftWorld
