model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularActorModularCriticModel
  shaping_reward: 0
  use_args: false
name: craft_mamc-19-forcestop-0
recipes: resources/craft/recipes.yaml
seed: 19
trainer:
  hints: resources/craft/hints.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: CraftWorld
