model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularACModel
  shaping_reward: 1.0
  use_args: false
name: craft_modular-4-1.0
recipes: resources/craft/recipes.yaml
seed: 4
trainer:
  hints: resources/craft/hints.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: CraftWorld
