model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularActorModularCriticModel
  shaping_reward: 0.1
  use_args: false
name: light_modular-17-forcestop-0.1
recipes: resources/light/recipes.yaml
seed: 17
trainer:
  hints: resources/light/hints.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: LightWorld
