model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularActorModularCriticModel
  shaping_reward: 0
  use_args: false
name: craft_mamc-minimal_forcestop-11
recipes: resources/craft/recipes.yaml
seed: 11
trainer:
  hints: resources/craft/hints-minimal.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: CraftWorld
