name: craft_modular-minimal-7
recipes: "resources/craft/recipes.yaml"
seed: 7
world: 
  name: CraftWorld 
model: 
  name: ModularACModel
  use_args: false
  featurize_plan: false
  max_subtask_timesteps: 15
  baseline: state
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/craft/hints-minimal.yaml"
  max_timesteps: 100
