model:
  baseline: state
  featurize_plan: false
  max_subtask_timesteps: 15
  name: ModularActorModularCriticModel
  reward_shaping: 0
  use_args: false
name: light_mamc-minimal_forcestop-16
recipes: resources/light/recipes.yaml
seed: 16
trainer:
  hints: resources/light/hints-minimal.yaml
  improvement_threshold: 0.8
  max_timesteps: 100
  name: CurriculumTrainer
  use_curriculum: true
world:
  name: LightWorld
